version: "3"

services:
  web:
    container_name: barcode
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    
  mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017:27017"